# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3-rc-3
loader_version=0.19.4
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_version=1.0.35
maven_group=fr.madu59
archives_base_name=ptp

# Dependencies
fabric_version=0.160.5+26.3
modmenu_version = 21.0.0-beta.1

modrinth_id = preyrsIh
curseforge_id = 1348218